/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAMC21 has 9 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8

#define CHG_24V_IN_SENS GPIO(GPIO_PORTA, 2)
#define VREF_2V5 GPIO(GPIO_PORTA, 3)
#define P_SENS GPIO(GPIO_PORTA, 4)
#define IN_24V_SENS GPIO(GPIO_PORTA, 5)
#define OUT_24V_SENS GPIO(GPIO_PORTA, 6)
#define CHG_OUT_SENS GPIO(GPIO_PORTA, 7)
#define FG_SDA GPIO(GPIO_PORTA, 8)
#define FG_SCL GPIO(GPIO_PORTA, 9)
#define FG_EXT_EN GPIO(GPIO_PORTA, 10)
#define AFE_EXT_EN GPIO(GPIO_PORTA, 11)
#define AFE_DDSG GPIO(GPIO_PORTA, 12)
#define AFE_DCHG GPIO(GPIO_PORTA, 13)
#define AFE_SDA GPIO(GPIO_PORTA, 16)
#define AFE_SCL GPIO(GPIO_PORTA, 17)
#define AFE_CFETOFF GPIO(GPIO_PORTA, 18)
#define AFE_HDQ GPIO(GPIO_PORTA, 19)
#define FLASH_CS GPIO(GPIO_PORTA, 20)
#define FLASH_MOSI GPIO(GPIO_PORTA, 21)
#define FLASH_MISO GPIO(GPIO_PORTA, 22)
#define FLASH_CLK GPIO(GPIO_PORTA, 23)
#define AFE_DPCHG GPIO(GPIO_PORTA, 24)
#define AFE_DPDSG GPIO(GPIO_PORTA, 25)
#define MCU_DDSG GPIO(GPIO_PORTB, 0)
#define MCU_DCHG GPIO(GPIO_PORTB, 1)
#define MCU_PDSG GPIO(GPIO_PORTB, 2)
#define MCU_PCHG GPIO(GPIO_PORTB, 3)
#define MAX14752_OUT GPIO(GPIO_PORTB, 5)
#define INA225_OUT GPIO(GPIO_PORTB, 9)
#define SDA_B_24V_POT GPIO(GPIO_PORTB, 12)
#define SCL__B_24V_POT GPIO(GPIO_PORTB, 13)
#define FET_DRV_FAULT GPIO(GPIO_PORTB, 14)
#define BMS_SHDN GPIO(GPIO_PORTB, 15)
#define SDA_CHG_POT GPIO(GPIO_PORTB, 16)
#define SCL_CHG_POT GPIO(GPIO_PORTB, 17)
#define B_SENS_EN GPIO(GPIO_PORTB, 18)
#define FLASH_WP GPIO(GPIO_PORTB, 19)
#define FLASH_HOLD GPIO(GPIO_PORTB, 20)
#define P_SENS_EN GPIO(GPIO_PORTB, 21)
#define V12_STAT GPIO(GPIO_PORTB, 22)
#define V12_EN GPIO(GPIO_PORTB, 23)
#define B_24V_FAULT GPIO(GPIO_PORTB, 24)
#define MCU_B_24V_SHDN GPIO(GPIO_PORTB, 25)
#define AFE_RST GPIO(GPIO_PORTB, 31)
#define OR_OUT_SENS GPIO(GPIO_PORTC, 0)
#define BAT_SENS GPIO(GPIO_PORTC, 1)
#define P_OUT_SENS GPIO(GPIO_PORTC, 2)
#define IN_24V_SENS_EN GPIO(GPIO_PORTC, 6)
#define OR_OUT_SENS_EN GPIO(GPIO_PORTC, 7)
#define AFE_ALERT GPIO(GPIO_PORTC, 8)
#define MCU_CHG_SHDN GPIO(GPIO_PORTC, 9)
#define BAT_24V_EN GPIO(GPIO_PORTC, 10)
#define OR_LINE_FAULT GPIO(GPIO_PORTC, 11)
#define CHG_IN_24V_SENS_EN GPIO(GPIO_PORTC, 12)
#define CHG_OUT_SENS_EN GPIO(GPIO_PORTC, 13)
#define P_OUT_SENS_EN GPIO(GPIO_PORTC, 14)
#define OUT_24V_SENS_EN GPIO(GPIO_PORTC, 15)
#define MAX14752_S0 GPIO(GPIO_PORTC, 16)
#define MAX14752_S1 GPIO(GPIO_PORTC, 17)
#define MAX14752_S2 GPIO(GPIO_PORTC, 18)
#define A_3V3_EN GPIO(GPIO_PORTC, 19)
#define CHG_STAT1 GPIO(GPIO_PORTC, 20)
#define CHG_STAT2 GPIO(GPIO_PORTC, 21)
#define LINE_24V_EN GPIO(GPIO_PORTC, 24)
#define OR_BAT_FAULT GPIO(GPIO_PORTC, 25)
#define AFE_DFETOFF GPIO(GPIO_PORTC, 26)
#define AFE_WAKE GPIO(GPIO_PORTC, 27)
#define MCU_FUSE GPIO(GPIO_PORTC, 28)

#endif // ATMEL_START_PINS_H_INCLUDED
